name: Release latest

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Publish latest release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: luna-artifacts
          path: ./dist/

      - name: Publish latest release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Latest Release
          files: ./dist/**
